#!/bin/sh

#JACK+PulseAudio
pactl load-module module-jack-sink channels=2
pactl load-module module-jack-source channels=2
pacmd set-default-sink jack_out
pacmd set-default-source jack_in
#sleep 2;ln -s /usr/bin/pulseaudio /tmp &
#sleep 5;/tmp/pulseaudio --start & 
#pulseaudio --start & 
sleep 5;jack_control start &
sudo schedtool -R -I -n 4 -p 25 `pidof jackdbus`
jack_control eps realtime true
jack_control ds alsa
jack_control dps device hw:0 
jack_control dps rate 192000
jack_control dps nperiods 3 
jack_control dps period 1024